// <auto-generated />
using Commander.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Commander.Migrations
{
    [DbContext(typeof(CommanderContext))]
    partial class CommanderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("Commander.Models.Command", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("HowTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Commands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HowTo = "howTo1",
                            Line = "myLine1",
                            Platform = "platform1"
                        },
                        new
                        {
                            Id = 2,
                            HowTo = "howTo2",
                            Line = "myLine2",
                            Platform = "platform2"
                        },
                        new
                        {
                            Id = 3,
                            HowTo = "howTo3",
                            Line = "myLine3",
                            Platform = "platform3"
                        },
                        new
                        {
                            Id = 4,
                            HowTo = "howTo4",
                            Line = "myLine4",
                            Platform = "platform4"
                        },
                        new
                        {
                            Id = 5,
                            HowTo = "howTo5",
                            Line = "myLine5",
                            Platform = "platform5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
